[DEFAULT]
input_dir = "path/to/your/input/folder"
output_dir = "path/to/your/output/folder"
cache_dir = "path/to/your/cache/folder"
exclude = [".vscode", ".idea", "venv", "test", "moe_utils", "img", "build"]
enable_extern_7z_use = true
extern_7z_executable_path = "7z"
