[tool.poetry]
name = "moxmoe-epub-manga-repacker"
version = "0.1.12"
description = "A manga repacker of EPUB comics downloaded from vol.moe/mox.moe/kox.moe."
authors = ["Haoyi HAN <54799247+Haoyi-Han@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
rich = "^13.7.0"
lxml = "^4.9.3"
tenacity = "^8.2.3"


[tool.poetry.group.dev.dependencies]
pywin32 = "^306"
comtypes = "^1.2.0"
setuptools = "^69.0.2"
cx-freeze = "^6.15.11"
nuitka = "^1.9.4"
zstandard = "0.21.0"


[[tool.poetry.source]]
name = "mirrors"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "default"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
