[tool.poetry]
name = "moxmoe-epub-manga-repacker"
version = "0.1.10"
description = "A manga repacker of EPUB comics downloaded from vol.moe/mox.moe/kox.moe."
authors = ["Haoyi HAN <54799247+Haoyi-Han@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9"
rich = "^13.4.2"
configparser = "^5.3.0"
retry = "^0.9.2"
beautifulsoup4 = "^4.12.2"
lxml = "^4.9.2"


[tool.poetry.group.dev.dependencies]
pywin32 = "^306"
comtypes = "^1.2.0"
setuptools = "^68.0.0"
cx-freeze = "^6.15.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
